//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lessons()
        {
            this.Progress = new HashSet<Progress>();
        }
    
        public int lesson_id { get; set; }
        public Nullable<int> timetable_id { get; set; }
        public string short_name { get; set; }
        public string name { get; set; }
        public Nullable<int> homework_id { get; set; }
        public Nullable<int> week_num { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Homeworks Homeworks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Progress> Progress { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
