//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parents
    {
        public int parant_id { get; set; }
        public int user_id { get; set; }
        public int child_id { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Students Students { get; set; }
    }
}
