//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Lessons = new HashSet<Lessons>();
        }
    
        public int timetable_id { get; set; }
        public int class_id { get; set; }
        public int weekday_id { get; set; }
        public int lesson_number { get; set; }
        public int subject_id { get; set; }
        public int classroom_id { get; set; }
        public Nullable<int> week_number { get; set; }
    
        public virtual CallSchedule CallSchedule { get; set; }
        public virtual Classes Classes { get; set; }
        public virtual Classrooms Classrooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lessons> Lessons { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Weekdays Weekdays { get; set; }
    }
}
