//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Авторизация_кассиров
    {
        public System.Guid id_записи { get; set; }
        public System.DateTime Время_авторизации { get; set; }
        public Nullable<System.DateTime> Время_выхода_из_системы { get; set; }
        public int Номер_кассы { get; set; }
        public System.Guid id_сотрудника { get; set; }
    
        public virtual Касса Касса { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
