//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Возврат
    {
        public System.Guid id { get; set; }
        public string Причина { get; set; }
        public System.DateTime Дата_возврата { get; set; }
        public int Сумма_возврата { get; set; }
        public int Номер_кассы { get; set; }
        public long C__транзакции { get; set; }
    
        public virtual Касса Касса { get; set; }
        public virtual Покупка Покупка { get; set; }
    }
}
