//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Группы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Группы()
        {
            this.Дисциплина_в_семестре = new HashSet<Дисциплина_в_семестре>();
            this.Студенты_в_группах = new HashSet<Студенты_в_группах>();
            this.Студенты_кураторы = new HashSet<Студенты_кураторы>();
        }
        public System.Guid ID_группы { get; set; }

        public System.Guid ID_института { get; set; }

        public string Наименование { get; set; }

        public int Год_поступления { get; set; }

        public int Длительность_обучения { get; set; }

        public int Код_формы_обучения { get; set; }

        public string Код_направления_подготовки { get; set; }
    
        public virtual Институты Институты { get; set; }
        public virtual Направления_подготовки Направления_подготовки { get; set; }
        public virtual Формы_обучения Формы_обучения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Дисциплина_в_семестре> Дисциплина_в_семестре { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студенты_в_группах> Студенты_в_группах { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студенты_кураторы> Студенты_кураторы { get; set; }
    }
}
