//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Дисциплина_в_семестре
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Дисциплина_в_семестре()
        {
            this.Зачетная_ведомость = new HashSet<Зачетная_ведомость>();
        }
    
        public System.Guid ID_дисциплины_в_семестре { get; set; }
        public System.Guid ID_лектора { get; set; }
        public System.Guid ID_группы { get; set; }
        public string Код_дисциплины { get; set; }
        public int Номер_семестра_обучения { get; set; }
        public int Количество_часов_в_неделю { get; set; }
        public int Код_формы_контроля { get; set; }
    
        public virtual Группы Группы { get; set; }
        public virtual Дисциплины Дисциплины { get; set; }
        public virtual Преподаватели Преподаватели { get; set; }
        public virtual Форма_контроля Форма_контроля { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Зачетная_ведомость> Зачетная_ведомость { get; set; }
    }
}
