//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Зачетная_ведомость
    {
        public System.Guid ID_студента { get; set; }
        public System.Guid ID_группы { get; set; }
        public System.Guid ID_дисциплины_в_семестре { get; set; }
        public System.DateTime Дата_сдачи { get; set; }
        public int Балл { get; set; }
        public int Отметка { get; set; }
        public string Литера { get; set; }
    
        public virtual Дисциплина_в_семестре Дисциплина_в_семестре { get; set; }
        public virtual Студенты_в_группах Студенты_в_группах { get; set; }
    }
}
