//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Покупка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Покупка()
        {
            this.Возврат = new HashSet<Возврат>();
        }
    
        public long C__транзакции { get; set; }
        public System.DateTime Время_покупки { get; set; }
        public Nullable<long> C__карты_оплаты { get; set; }
        public int Стоимость { get; set; }
        public System.Guid id_корзины { get; set; }
        public int Номер_кассы { get; set; }
        public Nullable<long> Номер_карты { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Возврат> Возврат { get; set; }
        public virtual Дисконтная_карта Дисконтная_карта { get; set; }
        public virtual Касса Касса { get; set; }
        public virtual Корзина Корзина { get; set; }
    }
}
