//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты_в_группах
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Студенты_в_группах()
        {
            this.Зачетная_ведомость = new HashSet<Зачетная_ведомость>();
        }
    
        public System.Guid ID_студента { get; set; }
        public System.Guid ID_группы { get; set; }
        public int Код_формы_оплаты { get; set; }
    
        public virtual Группы Группы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Зачетная_ведомость> Зачетная_ведомость { get; set; }
        public virtual Студенты Студенты { get; set; }
        public virtual Формы_оплаты Формы_оплаты { get; set; }
    }
}
