//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        public long Код_товара { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Количество { get; set; }
        public string Название_категории { get; set; }
        public Nullable<decimal> Цена { get; set; }
    }
}
