//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар_в_корзине
    {
        public int Количество { get; set; }
        public long Код_товара { get; set; }
        public System.Guid id_корзины { get; set; }
        public decimal Цена { get; set; }
    
        public virtual Корзина Корзина { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
