//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Цена
    {
        public System.Guid id_цены { get; set; }
        public decimal Цена1 { get; set; }
        public System.DateTime Дата_начала_действия_цены { get; set; }
        public Nullable<System.DateTime> Дата_окончания_действия_цены { get; set; }
        public long Код_товара { get; set; }
    
        public virtual Товар Товар { get; set; }
    }
}
